### ISSUE TITLE
Can´t seem to be able to choose MIDI port

### ISSUE THREAD

**Issue by freber1972** [pete-cain/VZEdit#2]
Hi, 
Newbie at this but love the layout and idéa of the editor, but can not choose MIDI out (it´s blank, nothing to select).

Idéas to make it work ?

Kind regards
/Fredrik

**Comment by pete-cain** [comment]
I have re-implemented the MIDI API to use the Web MIDI API. It should now work for the mainstream browsers. 
You can access it directly here: https://pete-cain.github.io/VZEdit/
Make sure you enable sysex on menu 3 of your VZ. (Needs to be re-enabled everytime you turn it on)
I hope you will have fun.

**Comment by freber1972** [comment]
Tnx, it sure does super, very nice!
Now i only need to understand how to program nice sounds for my VZ1 beast!

Med vänliga hälsningar, Kind regards
/Fredrik Bergfeldt

 

    Den måndag 30 november 2020 22:09:04 CET, Pete Kuhn <notifications@github.com> skrev:  
 
 


I have re-implemented the MIDI API to use the Web MIDI API. It should now work for the mainstream browsers.
You can access it directly here: https://pete-cain.github.io/VZEdit/
Make sure you enable sysex on menu 3 of your VZ. (Needs to be re-enabled everytime you turn it on)
I hope you will have fun.
